version: "0.7.5"

services:
  stock:
    # image: 
    build:
      context: ./stock
      dockerfile: dockerfile
    container_name: subdomain_stock
    restart: always
    environment:
      - APP_NAME=FlaskApp
    ports:
      - 80:8080
    networks:
      - web_service

networks:
  web_service:
    external: true
