##### dockerfile #####

FROM python:3.7.13-slim-bullseye
# RUN apk update && apk add python3-dev gcc libc-dev libffi-dev

WORKDIR /stock
ADD . /stock

# ENV FLASK_APP=backend/main
ENV FLASK_ENV=development

RUN pip install -r requirements.txt
CMD ["python", "./backend/main.py"]
# CMD ["flask", "run"]
