##### dockerfile #####

FROM python:3.7.13-slim-bullseye
# python:alpine will cost lot of time to build image and have no gcc package

WORKDIR /stock
ADD . /stock

# fix ModuleNotFoundError: No module named
ENV PYTHONPATH="$PYTHONPATH:/stock"

# ENV FLASK_APP=backend/main
ENV FLASK_DEBUG=True

RUN pip install -r requirements.txt
CMD ["python", "./backend/main.py"]
# CMD ["flask", "run"]
